### ISSUE TITLE
Could not find type 'Ignition.Foundation.Authentication.Processors.GoogleIdentityProviderProcessor, Ignition.Foundation.Authentication'

### ISSUE THREAD

**Issue by sjagannathan** [georgechang/Ignition.Foundation.Authentication#2]
Hi Geogre, While trying to use your module for google federated authentication, I'm receiving following error. 
Could not find type 'Ignition.Foundation.Authentication.Google.GoogleIdentityProviderProcessor, Ignition.Foundation.Authentication'
Please advise

**Comment by georgechang** [comment]
Fixed with #3. Sorry about that!
